export enum TipoGasto {
  ALQUILER = 'ALQUILER',
  MECANICO = 'MECANICO',
  COMISION = 'COMISION',
  COMIDA = 'COMIDA',
  MATERIALES = 'MATERIALES',
  TRASPASO = 'TRASPASO',
  REPUESTOS = 'REPUESTOS',
  MANTENIMIENTO = 'MANTENIMIENTO',
  OTROS = 'OTROS'
} 